#!/bin/sh
SRCDIR=`dirname $0`
if test $# -gt 0; then
  VER="$*"
elif test -f "${SRCDIR}/.tarball-version"; then
  VER=`cat "${SRCDIR}/.tarball-version"`
elif test -r "${SRCDIR}/.git" && test -x "`which git`" ; then
  git update-index -q --refresh
  if ! VER=`git describe --tags --dirty 2>/dev/null`; then
    COMMIT=`git rev-parse --short HEAD`
    DIRTY=`git diff --quiet HEAD || echo "-dirty"`
    VER=`sed -n '1,/RE/s/Version \(.*\)/\1/p' ${SRCDIR}/NEWS`-git-${COMMIT}${DIRTY}
  fi
fi
VER=`printf %s "$VER" | head -n1`
printf %s "$VER"
